### PR TITLE
Changing index.html and adding new files, not done with landing page

### PR DESCRIPTION
**Pull request by yaaowusu00**
This PR was made just so everyone can update their files locally. I'm not done with the landing page (right now I just have a rough outline) but if anyone has any suggestions, let me know!

### CODE REVIEW

**Comment by yaaowusu00** [comment]
I also realize that I should have made the branch name more specific since we are only using one branch per PR now

**Comment by fancast** [comment]
> I also realize that I should have made the branch name more specific since we are only using one branch per PR now

I like the design of the landing page so far! Your mock design is coming to life!

A few things to note:
- Are you able to remove the scroll bar where the three blue circles are? 
image
- Is a mobile oriented design an option?

**Comment by yaaowusu00** [comment]
Thanks! About the scrolling part- I was just playing around with the overflow property.  I already changed a lot since this last PR (including removing the scrolling part) So I’ll update it tomorrow.  I’ve also been trying to do everything in terms of vw and vh so it scales to size. I’ll have to see if the circles look too small on a phone though.

**Comment by fancast** [comment]
> Thanks! About the scrolling part- I was just playing around with the overflow property. I already changed a lot since this last PR (including removing the scrolling part) So I’ll update it tomorrow. I’ve also been trying to do everything in terms of vw and vh so it scales to size. I’ll have to see if the circles look too small on a phone though.

I saw the video for the updated version in the group chat. You can use the developer options and change the window to an iPhone screen size to see if the circles are small.

**Review by fancast — APPROVED** [review]
Approved!

**Pull request merged**
